### ISSUE TITLE
Quiz 2 File

### ISSUE THREAD

**Issue by Zilver1** [viraajsinghgill/Improving-Deep-Neural-Networks-Hyperparameter-Tuning-Regularization-and-Optimization#1]
Contributing Quiz 2 file
[Week 2 Quiz - Optimization algorithms.pdf](https://github.com/viraajsinghgill/Improving-Deep-Neural-Networks-Hyperparameter-Tuning-Regularization-and-Optimization/files/13530279/Week.2.Quiz.-.Optimization.algorithms.pdf)

**Comment by viraajsinghgill** [comment]
adding quiz 2
